# Generated by Django 4.2.1 on 2023-07-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_grade',
        ),
        migrations.AddField(
            model_name='choice',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
